overrides:
  vite: npm:@voidzero-dev/vite-plus-core@latest

registries:
  '@packtrans': https://npm.pkg.github.com

lockfileIncludeTarballUrl: true

allowBuilds:
  esbuild: true
  sharp: true
  workerd: true

minimumReleaseAgeExclude:
  - '@packtrans/glossary@0.0.8'
